# Generated by Django 2.0 on 2018-01-21 22:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('payables', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='InvoiceJournal',
            new_name='PurchaseInvoiceJournal',
        ),
        migrations.AlterModelOptions(
            name='purchaseinvoicejournal',
            options={'verbose_name_plural': 'Purchase Invoice Journal'},
        ),
    ]
