# Generated by Django 2.0 on 2018-03-12 23:06

from django.db import migrations, models
import django_countries.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Address',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('address', models.CharField(blank=True, default='', max_length=100)),
                ('address2', models.CharField(blank=True, default='', max_length=100)),
                ('city', models.CharField(blank=True, default='', max_length=60)),
                ('post_code', models.CharField(blank=True, default='', max_length=16)),
                ('country', django_countries.fields.CountryField(blank=True, max_length=2)),
                ('email', models.EmailField(blank=True, default='', max_length=120)),
                ('phone_no', models.CharField(blank=True, default='', max_length=20)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('address', models.CharField(blank=True, default='', max_length=100)),
                ('address2', models.CharField(blank=True, default='', max_length=100)),
                ('city', models.CharField(blank=True, default='', max_length=60)),
                ('post_code', models.CharField(blank=True, default='', max_length=16)),
                ('country', django_countries.fields.CountryField(blank=True, max_length=2)),
                ('email', models.EmailField(blank=True, default='', max_length=120)),
                ('phone_no', models.CharField(blank=True, default='', max_length=20)),
                ('first_name', models.CharField(max_length=60)),
                ('last_name', models.CharField(blank=True, default='', max_length=60)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
