# Generated by Django 2.0 on 2018-03-12 23:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('receivables', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='type',
            field=models.PositiveSmallIntegerField(choices=[(100, 'Company'), (200, 'Person')], default=100),
        ),
    ]
