# Generated by Django 2.0 on 2018-03-01 23:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('shared', '__first__'),
        ('receivables', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.CharField(max_length=32)),
                ('name', models.CharField(max_length=128)),
                ('address', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='customer', to='shared.Address')),
                ('billing_address', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='customer_bill', to='shared.Address')),
                ('shipping_address', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='customer_ship', to='shared.Address')),
            ],
        ),
        migrations.AlterField(
            model_name='salesinvoicejournal',
            name='attachment',
            field=models.FileField(blank=True, null=True, upload_to=''),
        ),
    ]
